site_name: Debaters
theme:
  name: material
  font:
    code: Roboto Mono
  icon: site/assets/images/favicon.svg
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
plugins:
  - search