site_name: Debaters
site_description: Debaters Discord
site_author: Biune#0001

nav:
  - 'Home': '../'
  - 'About': 'about.md'
  - 'Discord': 'https://discord.gg/MVRsuYbCRM'
  - 'Rules': 'rules.md'
  - 'Staff List': 'staff_list.md'
  - 'Moderator': 'moderator.md'

theme:
  name: gitbook

plugins:
  - awesome-pages
  - autolinks 
  - redirects:
      redirect_maps:
        'discord.md': 'https://discord.gg/MVRsuYbCRM'
        'gist.md': ''

