site_name: Debaters
theme:
  name: material
  font:
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
  favicon: assets/resized.png
plugins:
  - search